### PR TITLE
Update API version to 2.27

### PR DESCRIPTION
**Pull request by bhelx**
* Adds support for Items and item-backed-add-ons
* Adds quantity based pricing support
* Adds support for "Avalara for Communications" integration

### CODE REVIEW

**Comment by bhelx** [comment]
I've done some over-the-shoulder testing for this and I've added unit tests. Is there anything else I can do to ensure quality? Does this project have integration tests? Let me know what the process is.

**Comment by bhelx** [comment]
Hi, checking in on this. Anything else I need to do?

**Comment by cristiangraz** [comment]
Thanks @bhelx!

**Comment by bhelx** [comment]
Thanks!

**Pull request merged**
