### PR TITLE
Refactor NullTime to not use a *time.Time.

### PR DESCRIPTION
**Pull request by jimmysawczuk**
Hi there! Wanted to see if you would consider reworking `NullTime` to not use a `*time.Time` and instead follow the pattern of `sql.NullString`, etc. Here's my take at it. Let me know if there's anything I'm missing. Thank you!

### CODE REVIEW

**Comment by cristiangraz** [comment]
Hi @jimmysawczuk, This change makes a lot of sense, especially for consistency with the other types.

Have you seen https://github.com/blacklightcms/recurly/issues/116 or https://github.com/blacklightcms/recurly/pull/118?

I'll push up this change to that branch shortly since this will be a breaking change against `master` and I'd prefer to incorporate it into the in progress PR so we only have a single breaking change.

Similarly would love to hear your thoughts on the refactor issue or PR as a lot is changing!

**Comment by cristiangraz** [comment]
Added here: https://github.com/blacklightcms/recurly/pull/118/commits/5912319154983b7d6cd50f156c7737bfd0613c59

Note one change I made in the process is to add a `Value()` to all null types, and `Int()`/`Time()`/`Bool()` methods (respective to `NullInt`, `NullTime`, and `NullBool`) so that the internal values are tucked away.

I've seen several users do this:

```go
recurly.NullInt{Int: 0}
```
Thinking they have a valid int with a value of `0`, but because they omitted the `Valid: true` field they have a bug. I've done this myself and can be quite difficult to debug.

Instead:

```go
recurly.NewInt(0)
recurly.Int() // returns 0
recurly.Value() returns 0, true
```

**Comment by jimmysawczuk** [comment]
Seems like a reasonable change to me, and I definitely agree with standardizing it across all the types. When do you expect this to land in master?

**Comment by cristiangraz** [comment]
I'd love to see it merged next week, but because this library handles billing/payments I want to be as thorough as possible and give the community a chance to comment and try out given the large amount of changes. Ultimately will depend on what types of comments/feedback comes back.

If you want to try it out though, you can definitely point to the `refactor` branch and start using it now! I'm hoping to find time to migrate our internal code to use the new `refactor` branch tomorrow for initial production testing.

**Comment by jimmysawczuk** [comment]
One thing I just thought of: if you add a `Value()` method to those types, you can't implement [`driver.Valuer`](https://golang.org/pkg/database/sql/driver/#Valuer) later, which might be handy. Just worth a thought.

**Pull request closed without merging**
